
project_id = "oygmfedzibzxojqirgxo"

[functions.get-app-url]
verify_jwt = true

[functions.send-whatsapp-otp]
verify_jwt = true

[functions.verify-whatsapp-otp]
verify_jwt = false

[functions.customer-send-whatsapp-otp]
verify_jwt = false

[functions.customer-verify-whatsapp-otp]
verify_jwt = false

[functions.gupshup-webhook]
verify_jwt = false

[functions.send-gupshup-notification]
verify_jwt = true
